name: "Kind Cluster with internal container registry"
description: "Create a kind (Kubernetes IN Docker) cluster with an internal container registry"
author: "The Helm authors"
inputs:
  kind_version:
    description: 'The version of kind to use'
    required: false
    default: 'v0.17.0'
  kubectl_version:
    description: 'The version of kubectl to use'
    required: false
    default: 'v1.25.3'
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Install Helm
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1

    - name: Install yq
      uses: dcarbone/install-yq-action@v1.1.0

    - name: Set up Registry Container
      shell: bash
      run: |
        docker run -d --restart=always -p "127.0.0.1:5001:5000" --name kind-registry registry:2

    - name: Create kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        version: ${{ inputs.kind_version }}
        kubectl_version: ${{ inputs.kubectl_version }}
        config: ${{ github.action_path }}/kind-config.yaml

    - name: Set up Local Registry
      shell: bash
      run: |
        # https://kind.sigs.k8s.io/docs/user/local-registry/
        docker network connect kind kind-registry
        kubectl apply -f ${{ github.action_path }}/configmap-registry.yaml
