name: "Kind Cluster with internal container registry"
description: "Create a kind (Kubernetes IN Docker) cluster with an internal container registry"
author: "bakito"
inputs:
  kind_version:
    description: 'The version of kind to use'
    required: false
    # renovate: github-releases kubernetes-sigs/kind
    default: 'v0.30.0'
  kubectl_version:
    description: 'The version of kubectl to use'
    required: false
    # renovate: custom.k8s kubectl
    default: 'v1.34.2'
  node_image:
    description: 'The version of node image to use'
    required: false
    # renovate: docker
    default: 'kindest/node:v1.34.2'
  ingress_enabled:
    description: 'enable ingress for the cluster'
    required: false
    default: false
  ingress_version:
    description: 'The ingress controller version (git tag)'
    required: false
    # renovate: helm ingress-nginx https://kubernetes.github.io/ingress-nginx
    default: 4.14.1
  registry_image:
    description: 'The registry docker image to be used'
    required: false
    # renovate: docker
    default: 'registry:3'
  debug:
    description: enable debug output for helm chart installation
    required: false
    default: false
outputs:
  ingress_class_name:
    description: 'The name of the ingress class'
    value: 'nginx'
  registry:
    description: 'The address of the docker registry'
    value: 'localhost:5001'
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4.3.1

    - name: Install jq
      uses: dcarbone/install-jq-action@v3.2.0

    - name: Install yq
      uses: dcarbone/install-yq-action@v1.3.1

    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.2.13

    - name: Set up Registry Container
      shell: bash
      run: |
        docker run -d --restart=always -p "127.0.0.1:5001:5000" --name kind-registry ${{ inputs.registry_image }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.13.0
      with:
        version: ${{ inputs.kind_version }}
        kubectl_version: ${{ inputs.kubectl_version }}
        node_image: ${{ inputs.node_image }}
        config: ${{ github.action_path }}/kind-config.yaml
        verbosity: ${{ inputs.debug == 'true' && '9' || '0' }}

    - name: Set up Local Registry
      shell: bash
      run: |
        # https://kind.sigs.k8s.io/docs/user/local-registry/
        docker network connect kind kind-registry
        kubectl apply -f ${{ github.action_path }}/configmap-registry.yaml ${{ inputs.debug == 'true' && '-v 9' || '' }}

    - name: Set up Ingress
      if: ${{ inputs.ingress_enabled == 'true' }}
      shell: bash
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        echo "Install ingress-nginx helm chart ${{ inputs.ingress_version }}"
        helm install ingress-nginx ingress-nginx/ingress-nginx --version ${{ inputs.ingress_version }} --wait=watcher --timeout=90s ${{ inputs.debug == 'true' && '--debug' || '' }} \
          --create-namespace -n ingress-nginx \
          -f ${{ github.action_path }}/ingress-nginx-values.yaml \
          --set controller.progressDeadlineSeconds=600 ${{ inputs.debug == 'true' && '' || '> /dev/null' }}
        helm list -n ingress-nginx
