name: "Kind Cluster"
description: "Create a kind (Kubernetes IN Docker) cluster"
author: "bakito"
inputs:
  kind_version:
    description: 'The version of kind to use'
    required: false
    # renovate: github-releases kubernetes-sigs/kind
    default: 'v0.31.0'
  kind_cluster_name:
    description: 'The name of kind cluster'
    required: false
    default: 'chart-testing'
  kubectl_version:
    description: 'The version of kubectl to use'
    required: false
    # renovate: custom.k8s kubectl
    default: 'v1.35.2'
  node_image:
    description: 'The version of node image to use'
    required: false
    # renovate: docker
    default: 'kindest/node:v1.35.1'
  debug:
    description: enable debug output for helm chart installation
    required: false
    default: false
  docker_image_name:
    description: Name of the docker image to import to kind
    required: false
    default: ""
  docker_image_file:
    description: Name of the docker image file (tar) to import to kind
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4.3.1

    - name: Install jq
      uses: dcarbone/install-jq-action@v3.2.0

    - name: Install yq
      uses: dcarbone/install-yq-action@v1.3.1

    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.2.14

    - name: Create kind cluster
      uses: helm/kind-action@v1.14.0
      with:
        version: ${{ inputs.kind_version }}
        cluster_name: ${{ inputs.kind_cluster_name }}
        kubectl_version: ${{ inputs.kubectl_version }}
        node_image: ${{ inputs.node_image }}
        config: ${{ github.action_path }}/kind-config.yaml
        verbosity: ${{ inputs.debug == 'true' && '9' || '0' }}

    - name: Import docker image
      if: ${{ inputs.docker_image_name != '' }}
      shell: bash
      run: |
        if [["${{ inputs.docker_image_file }}" != ""]]; then
          docker load -i ${{ inputs.docker_image_file }}
        fi
        kind load docker-image ${{ inputs.docker_image_name }} --name ${{ inputs.kind_cluster_name }}