# Kong Helm Chart Values for KIND
image:
  repository: kong
  tag: "3.4"

env:
  database: "off"
  nginx_worker_processes: "1"
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  admin_gui_access_log: /dev/stdout
  portal_api_access_log: /dev/stdout
  proxy_error_log: /dev/stderr
  admin_error_log: /dev/stderr
  admin_gui_error_log: /dev/stderr
  portal_api_error_log: /dev/stderr

# Enable Ingress Controller
ingressController:
  enabled: true
  gatewayDiscovery:
    enabled: false  # Disabled to avoid split-release requirement
  env:
    kong_admin_token: kong-admin-token
    kong_admin_listen: "0.0.0.0:8001"

# Proxy service configuration for KIND
proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    nodePort: 30080
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    nodePort: 30443

# Admin API
admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
    nodePort: 30001

# Manager (GUI)
manager:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
    nodePort: 30002

# Portal
portal:
  enabled: false

# PostgreSQL (disabled for simplicity)
postgresql:
  enabled: false

# Resource limits for KIND
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
